# the following parameters are the same across the module #
root_dir: "./GitHub/trainings" # path to main dir of the project
metadata_dir: "./" # path to metadata dir of the project
PROJECT_NAME: "mouse-test-dataset"
PI_NAME: "Stanislav Zakharenko"
TASK_ID: "Training 1 - Demo"
PROJECT_LEAD_NAME: "NA"
DEPARTMENT: "Developmental Neurobiology"
LEAD_ANALYSTS: "Antonia Chroni, PhD"
GROUP_LEAD: "Cody A. Ramirez, PhD"
CONTACT_EMAIL: "antonia.chroni@stjude.org"
PIPELINE: "Training 1 - Demo"
START_DATE: "10/10/2024"
COMPLETION_DATE: "10/10/2024"
